// src/components/features/Chats/ChatsList/ChatsList.tsx
import { useEffect } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { Stack } from "@mui/material";

import { IChat } from "@/api/v1";
import { useChatsStore } from "@/store";

import { ChatsListItem } from "./ui";

/**
 * Chats list component
 */
export const ChatsList = () => {
  const navigate = useNavigate();
  const location = useLocation();

  const match = location.pathname.match(/\/chat\/(\d+)/);
  const currentChatId = match ? match[1] : null;

  const { chats, refetchChats, deleteChat } = useChatsStore();

  useEffect(() => {
    refetchChats();
  }, [refetchChats]);

  const onChatClick = (chat: IChat) => {
    navigate(`/chat/${chat.id}`);
  }

  const onDeleteHandler = (chat: IChat) => {
    deleteChat(chat);
  }

  return (
    <Stack className="flex flex-col w-48 h-full bg-gray-200 p-2 gap-2 overflow-auto flex-shrink-0">
      {chats.map((chat) => (
        <ChatsListItem
          key={chat.id}
          chat={chat}
          active={chat.id === currentChatId}
          onDelete={onDeleteHandler}
          onClick={onChatClick}
        />
      ))}
    </Stack>
  );
};

// src/components/chatsList/ChatsList.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import ChatsListItem from './ChatsListItem.vue';
import { TChat } from './chatsList.types';
import { mockChatsList } from '@/mock/chatsList';
import { useRoute } from 'vue-router';

const route = useRoute();
const currentChatId = computed(() => {
  if (route.params.id) {
    return route.params.id
  }

  return undefined;
});
const chats = ref<TChat[]>([]);

onMounted(() => {
  chats.value = mockChatsList;
});
</script>

<template>
  <div class='w-full grow-1 p-4 flex flex-col overflow-y-auto gap-2'>
    <ChatsListItem
      v-for='chat in chats'
      :key='chat.id'
      :item='chat'
      :active='!!chat.id && chat.id === currentChatId'
    />
  </div>
</template>
