// src/App.tsx
import { Stack } from "@mui/material";
import { AppRouterView } from "./router";
import { HashRouter } from "react-router-dom";
import { ChatsList } from "./components";
import { useEffect, useState } from "react";
import { AppLoader } from "./components/shared";
import { ThemeProvider } from "@/context/ThemeContext";

export const App = () => {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    window.ipcRenderer?.invoke('get:loading').then((loading) => {
      setLoading(loading.value);
    });

    window.ipcRenderer?.on('set-loading', (_, loading) => {
      setLoading(loading.value);
    });
  }, []);

  return (
    <ThemeProvider>
      <HashRouter>
        {loading
          ? <AppLoader />
          : (
            <Stack className="relative flex flex-col h-screen bg-gray-100">
              {/* <AppHeader /> */}

              <Stack direction="row" className="flex-grow h-full overflow-hidden">
                <ChatsList />
                <AppRouterView />
              </Stack>
            </Stack>
          )
        }
      </HashRouter>
    </ThemeProvider>
  );
};

// src/App.vue
<script setup lang="ts">
import { RouterView } from 'vue-router';
import AppHeader from './components/AppHeader.vue';
import { useCommonStore } from './store/common';
import MyScreenLoader from './components/shared/myScreenLoader.vue';
import AppSidebar from './components/AppSidebar.vue';

const commonStore = useCommonStore();
commonStore.setLoading(true);

setTimeout(() => {
  commonStore.setLoading(false);
}, 3000);
</script>

<template>
  <div class='w-screen h-screen flex flex-col'>
    <MyScreenLoader :show='commonStore.loading' />

    <AppHeader />

    <div class='flex flex-grow overflow-hidden'>
      <AppSidebar />

      <main class='flex-grow flex flex-col bg-white'>
        <!-- <div class='p-4 bg-gray-300'>
          Main Header
        </div> -->
        <RouterView />
      </main>
    </div>
  </div>
</template>

<style lang="scss">
#app {
  font-family: Roboto, sans-serif;
  font-weight: 400;
}
</style>
